# -*- coding: utf-8 -*-
"""Autoviz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njkA-SFIQeKCcluoJVZdyQC-H2OXd_2H
"""

!pip install autoviz

import seaborn as sns

df=sns.load_dataset('tips')

df.head()

df.to_csv('tips.csv')

from autoviz.AutoViz_Class import AutoViz_Class

"""AV=autoViz_clss()"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
filename = "sample_data/california_housing_train.csv"
sep = ","
dft = AutoViz_Class().AutoViz(
    filename
)